#!/bin/bash

# Save as build-openbox.sh

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Error handling
set -e
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    echo -e "${RED}Don't run as root${NC}"
    exit 1
fi

# Base packages
BASE_PACKAGES=(
    openbox
    obconf
    tint2
    nitrogen
    picom
    pcmanfm
    lxappearance
    xorg
    xorg-xinit
    arandr
    alacritty
    firefox
    networkmanager
    network-manager-applet
    volumeicon
    rofi
    dunst
    feh
    scrot
    ranger
    neofetch
    htop
    git
    base-devel
    pavucontrol
    pulseaudio
    pulseaudio-alsa
)

# Install base packages
echo -e "${BLUE}Installing base packages...${NC}"
for package in "${BASE_PACKAGES[@]}"; do
    if ! pacman -Qi "$package" >/dev/null 2>&1; then
        sudo pacman -S --noconfirm "$package"
    fi
done

# Create config directories
mkdir -p ~/.config/openbox
mkdir -p ~/.config/tint2
mkdir -p ~/.config/rofi
mkdir -p ~/.themes/Gruvbox/openbox-3
mkdir -p ~/.local/share/fonts
mkdir -p ~/Pictures/Screenshots

# Create autostart
cat > ~/.config/openbox/autostart << 'EOL'
#!/bin/bash

# Compositor
picom -b &

# Network Manager
nm-applet &

# Volume control
volumeicon &

# Panel
tint2 &

# Set wallpaper (create black wallpaper first time)
convert -size 1920x1080 xc:black ~/Pictures/wallpaper.png
nitrogen --set-zoom-fill ~/Pictures/wallpaper.png &

# Notifications
dunst &

# Optional: Start terminal
# alacritty &
EOL

chmod +x ~/.config/openbox/autostart

# Create tint2 config
cat > ~/.config/tint2/tint2rc << 'EOL'
#---- Generated by tint2conf e49d ----
# See https://gitlab.com/o9000/tint2/wikis/Configure for 
# full documentation of the configuration options.
#-------------------------------------
# Gradients
#-------------------------------------
# Backgrounds
# Background 1: Default task, Inactive taskbar, Normal task
rounded = 0
border_width = 1
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #282828 100
border_color = #282828 100
background_color_hover = #282828 100
border_color_hover = #282828 100
background_color_pressed = #282828 100
border_color_pressed = #282828 100

# Background 2: Active task, Active taskbar, Urgent task
rounded = 0
border_width = 1
border_sides = TBLR
border_content_tint_weight = 0
background_content_tint_weight = 0
background_color = #98971a 100
border_color = #98971a 100
background_color_hover = #98971a 100
border_color_hover = #98971a 100
background_color_pressed = #98971a 100
border_color_pressed = #98971a 100

#-------------------------------------
# Panel
panel_items = LTSC
panel_size = 100% 30
panel_margin = 0 0
panel_padding = 0 0 0
panel_background_id = 1
wm_menu = 1
panel_dock = 0
panel_position = bottom center horizontal
panel_layer = top
panel_monitor = all
primary_monitor_first = 0
autohide = 0
autohide_show_timeout = 0
autohide_hide_timeout = 0.5
autohide_height = 2
strut_policy = follow_size
panel_window_name = tint2
disable_transparency = 1
mouse_effects = 1
font_shadow = 0
mouse_hover_icon_asb = 100 0 10
mouse_pressed_icon_asb = 100 0 0

#-------------------------------------
# Taskbar
taskbar_mode = single_desktop
taskbar_hide_if_empty = 0
taskbar_padding = 0 0 2
taskbar_background_id = 1
taskbar_active_background_id = 2
taskbar_name = 1
taskbar_hide_inactive_tasks = 0
taskbar_hide_different_monitor = 0
taskbar_always_show_all_desktop_tasks = 0
taskbar_name_padding = 4 2
taskbar_name_background_id = 0
taskbar_name_active_background_id = 0
taskbar_name_font = sans bold 9
taskbar_name_font_color = #e3e3e3 100
taskbar_name_active_font_color = #ffffff 100
taskbar_distribute_size = 0
taskbar_sort_order = none
task_align = left

#-------------------------------------
# Task
task_text = 1
task_icon = 1
task_centered = 0
urgent_nb_of_blink = 100000
task_maximum_size = 150 35
task_padding = 2 2 4
task_tooltip = 1
task_thumbnail = 0
task_thumbnail_size = 210
task_font_color = #ffffff 100
task_background_id = 1
task_active_background_id = 2
task_urgent_background_id = 2
task_iconified_background_id = 1
mouse_left = toggle_iconify
mouse_middle = none
mouse_right = close
mouse_scroll_up = toggle
mouse_scroll_down = iconify
EOL

# Create Openbox theme
cat > ~/.themes/Gruvbox/openbox-3/themerc << 'EOL'
# Window geometry
padding.width: 4
padding.height: 4
border.width: 2
window.client.padding.width: 0
window.client.padding.height: 0
window.handle.width: 0

# Menu geometry
menu.border.width: 1
menu.overlap.x: -2
menu.overlap.y: 0

# Border colors
window.active.border.color: #98971a
window.inactive.border.color: #504945

# Window title
window.active.title.bg: flat solid
window.active.title.bg.color: #282828
window.active.title.separator.color: #282828
window.inactive.title.bg: flat solid
window.inactive.title.bg.color: #282828
window.inactive.title.separator.color: #282828

# Window text
window.active.label.bg: parentrelative
window.active.label.text.color: #ebdbb2
window.inactive.label.bg: parentrelative
window.inactive.label.text.color: #928374

# Menu settings
menu.items.bg: flat solid
menu.items.bg.color: #282828
menu.items.text.color: #ebdbb2
menu.items.active.bg: flat solid
menu.items.active.bg.color: #98971a
menu.items.active.text.color: #282828
EOL

# Create xinitrc
cat > ~/.xinitrc << 'EOL'
#!/bin/bash

# Load X resources
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Start pulseaudio if not running
pulseaudio --start &

# Set keyboard layout
setxkbmap us &

# Start Openbox
exec openbox-session
EOL

# Enable services
sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

# Create basic Openbox menu
cat > ~/.config/openbox/menu.xml << 'EOL'
<?xml version="1.0" encoding="UTF-8"?>
<openbox_menu xmlns="http://openbox.org/3.4/menu">
<menu id="root-menu" label="Openbox 3">
  <item label="Terminal">
    <action name="Execute">
      <command>alacritty</command>
    </action>
  </item>
  <item label="Web Browser">
    <action name="Execute">
      <command>firefox</command>
    </action>
  </item>
  <item label="File Manager">
    <action name="Execute">
      <command>pcmanfm</command>
    </action>
  </item>
  <separator />
  <menu id="applications" label="Applications" execute="xdg_menu --format openbox3-pipe --root-menu /etc/xdg/menus/arch-applications.menu" />
  <separator />
  <item label="Reconfigure">
    <action name="Reconfigure" />
  </item>
  <item label="Exit">
    <action name="Exit" />
  </item>
</menu>
</openbox_menu>
EOL

# Copy default rc.xml
cp /etc/xdg/openbox/rc.xml ~/.config/openbox/

# Create Openbox testing script
cat > ~/test-openbox.sh << 'EOL'
#!/bin/bash

echo "Testing Openbox setup..."

# Check services
echo "Checking services..."
services=("NetworkManager" "pulseaudio")
for service in "${services[@]}"; do
    if pgrep -x "$service" >/dev/null; then
        echo "✓ $service is running"
    else
        echo "✗ $service is not running"
    fi
done

# Check processes
echo -e "\nChecking processes..."
processes=("openbox" "tint2" "picom" "nm-applet" "volumeicon")
for proc in "${processes[@]}"; do
    if pgrep -x "$proc" >/dev/null; then
        echo "✓ $proc is running"
    else
        echo "✗ $proc is not running"
    fi
done

# Check config files
echo -e "\nChecking configuration files..."
configs=(
    "~/.config/openbox/rc.xml"
    "~/.config/openbox/menu.xml"
    "~/.config/openbox/autostart"
    "~/.config/tint2/tint2rc"
    "~/.xinitrc"
)

for config in "${configs[@]}"; do
    if [ -f $(eval echo $config) ]; then
        echo "✓ $(eval echo $config) exists"
    else
        echo "✗ $(eval echo $config) is missing"
    fi
done
EOL

chmod +x ~/test-openbox.sh

echo -e "${GREEN}Installation complete!${NC}"
echo -e "${YELLOW}To start Openbox:${NC}"
echo "$ startx"
echo -e "${YELLOW}To test the installation:${NC}"
echo "$ ./test-openbox.sh"
echo -e "${YELLOW}Basic keybindings:${NC}"
echo "Alt + Space       → Main menu"
echo "Alt + Tab         → Switch windows"
echo "Alt + F4          → Close window"
echo "Alt + Left/Right  → Switch desktops"
echo -e "${BLUE}Installation by: b0urn3${NC}"
echo "GitHub:    github.com/q4n0"
echo "Twitter:   @byt3s3c"
echo "Instagram: @onlybyhive"

trap - EXIT
